### ISSUE TITLE
Your dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by k-goncharova** [FlavioMacaubas/covid_19_paraiba#2]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/UQC1AK

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by FlavioMacaubas** [comment]
Hello,

Glad that i can help somehow, the dataset is update every day between 7pm ~
9pm (UTC -3). I'll make sure that a english/portuguese metadata is upload
to my repository as soon as possible.

Flávio Macaúbas

k-goncharova <notifications@github.com> escreveu no dia terça, 2/06/2020
à(s) 11:37:

**Comment by k-goncharova** [comment]
Hello Flávio, 

Thank you for your response and willingness to contribute. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. 

Additionally, you may want join our community of 1,000+ contributors in Slack https://www.coronawhy.org/join-the-fight and see if any other initiatives could be interesting to you. We have many cool people and interesting things going on :)

**Comment by FlavioMacaubas** [comment]
Hello,

I signed up for CoronaWhy Dataverse, my username is 'flaviomacaubas'.

I also register with the volunteer community.

Thank you,

Flávio Macaúbas

k-goncharova <notifications@github.com> escreveu no dia terça, 2/06/2020
à(s) 16:02:

**Comment by k-goncharova** [comment]
Welcome on board, Flávio! I've just granted the required permissions in Dataverse. Feel free to contact me if any questions.
